### ISSUE TITLE
Can't get rid of the translation bar on Firefox Nightly for Android

### ISSUE THREAD

**Issue by traysh** [FilipePS/Traduzir-paginas-web#159]
Hi,

I can't get rid of the translation bar (aka popup?) on Firefox Nightly for Android. The setting for it is not saved nor applied and is back to "on" when the browser is restarted.

Thanks

**Comment by ganon69** [comment]
That is correct. The setting does not get saved. Please fix this asap. Thank you.

**Comment by FilipePS** [comment]
I sent a new version that should solve this problem.
Did you notice any performance issues with the extension recently?

**Comment by ganon69** [comment]
Thanks I will check it out! Yes, there seems to be an issue when translating certain sites. The sites won’t translate unless you scroll up or down the page. Once you do that the translation appears immediately. Is this how it works…?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by traysh** [comment]
@FilipePS I still cannot see this version [here](https://addons.mozilla.org/pt-BR/firefox/addon/traduzir-paginas-web). 

Does it take too long to arrive?

**Comment by FilipePS** [comment]
> @FilipePS I still cannot see this version [here](https://addons.mozilla.org/pt-BR/firefox/addon/traduzir-paginas-web). 
> 
> Does it take too long to arrive?

Before a version is approved it undergoes an analysis.  It may take minutes or days.

**Comment by ganon69** [comment]
I can see the new version on my phone, but the problem is not fixed yet…

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by ganon69** [comment]
OK! Now working fine👍 Thank you
